development:
  adapter: postgresql
  encoding: unicode
  database: trinkit_development
  pool: 5
  username: admin
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: trinket_test
  pool: 5
  username: admin
  password: 
